"""Python client for the ZAP zero-copy application protocol.

Mirrors the Go implementation at github.com/luxfi/zap. Lets non-Go peers
(AI agents, ops scripts, FHE clients) read and build ZAP messages
without leaving Python.
"""

from .wire import (
    HEADER_SIZE,
    MAGIC,
    VERSION,
    DEFAULT_PORT,
    ALIGNMENT,
    FLAG_NONE,
    FLAG_COMPRESSED,
    FLAG_ENCRYPTED,
    FLAG_SIGNED,
    InvalidMagic,
    InvalidVersion,
    BufferTooSmall,
    OutOfBounds,
    InvalidOffset,
)
from .evm import (
    ADDRESS_SIZE,
    BLOOM_SIZE,
    HASH_SIZE,
    SIGNATURE_SIZE,
    Address,
    Bloom,
    Hash,
    Signature,
    ZERO_ADDRESS,
    ZERO_HASH,
    address_from_hex,
    hash_from_hex,
)
from .reader import Message, Object, List, parse
from .builder import Builder, ObjectBuilder, ListBuilder
from .schema import (
    BLOCK_HEADER_SCHEMA,
    Enum,
    Field,
    LOG_SCHEMA,
    Schema,
    Struct,
    StructBuilder,
    TRANSACTION_SCHEMA,
    Type,
    new_schema,
    new_struct_builder,
    type_size,
)

__all__ = [
    "HEADER_SIZE",
    "MAGIC",
    "VERSION",
    "DEFAULT_PORT",
    "ALIGNMENT",
    "FLAG_NONE",
    "FLAG_COMPRESSED",
    "FLAG_ENCRYPTED",
    "FLAG_SIGNED",
    "InvalidMagic",
    "InvalidVersion",
    "BufferTooSmall",
    "OutOfBounds",
    "InvalidOffset",
    "Message",
    "Object",
    "List",
    "parse",
    "Builder",
    "ObjectBuilder",
    "ListBuilder",
    "ADDRESS_SIZE",
    "HASH_SIZE",
    "SIGNATURE_SIZE",
    "BLOOM_SIZE",
    "Address",
    "Hash",
    "Signature",
    "Bloom",
    "ZERO_ADDRESS",
    "ZERO_HASH",
    "address_from_hex",
    "hash_from_hex",
    "Type",
    "Field",
    "Struct",
    "Enum",
    "Schema",
    "StructBuilder",
    "new_schema",
    "new_struct_builder",
    "type_size",
    "TRANSACTION_SCHEMA",
    "BLOCK_HEADER_SCHEMA",
    "LOG_SCHEMA",
]
