// Copyright (C) 2026, Lux Industries Inc. All rights reserved.
// See the file LICENSE for licensing terms.
//
// Code generated by github.com/luxfi/zap/v2/codegen — DO NOT EDIT.
// Source schema: ZKVMUTXO (kind=0x03, size=72).

package zkvmwire

import (
	"github.com/luxfi/zap"
	zapv2 "github.com/luxfi/zap/v2"
)

// KindZKVMUTXO is the wire discriminator for ZKVMUTXO.
const KindZKVMUTXO zapv2.KindByte = 0x03

// SizeZKVMUTXO is the fixed object payload size in bytes.
const SizeZKVMUTXO = 72

// ZKVMUTXOSchema is the v2 schema marker for ZKVMUTXO. Methods are constant-
// returning so concrete-typed [zapv2.Wrap[ZKVMUTXOSchema]] calls fold to
// literals at the call site.
type ZKVMUTXOSchema struct{}

func (ZKVMUTXOSchema) Kind() zapv2.KindByte { return KindZKVMUTXO }
func (ZKVMUTXOSchema) Size() int            { return SizeZKVMUTXO }
func (ZKVMUTXOSchema) Name() string         { return "ZKVMUTXO" }

// OffsetZKVMUTXO_OutputIndex is the byte offset of the OutputIndex field.
const OffsetZKVMUTXO_OutputIndex = 4

// OffsetZKVMUTXO_Height is the byte offset of the Height field.
const OffsetZKVMUTXO_Height = 8

// OffsetZKVMUTXO_TxID is the byte offset of the TxID field.
const OffsetZKVMUTXO_TxID = 16

// OffsetZKVMUTXO_CommitmentOff is the byte offset of the CommitmentOff field.
const OffsetZKVMUTXO_CommitmentOff = 48

// OffsetZKVMUTXO_CommitmentLen is the byte offset of the CommitmentLen field.
const OffsetZKVMUTXO_CommitmentLen = 52

// OffsetZKVMUTXO_CiphertextOff is the byte offset of the CiphertextOff field.
const OffsetZKVMUTXO_CiphertextOff = 56

// OffsetZKVMUTXO_CiphertextLen is the byte offset of the CiphertextLen field.
const OffsetZKVMUTXO_CiphertextLen = 60

// OffsetZKVMUTXO_EphemeralPKOff is the byte offset of the EphemeralPKOff field.
const OffsetZKVMUTXO_EphemeralPKOff = 64

// OffsetZKVMUTXO_EphemeralPKLen is the byte offset of the EphemeralPKLen field.
const OffsetZKVMUTXO_EphemeralPKLen = 68

// ZKVMUTXOSchemaFields is the namespace of every scalar field accessor for ZKVMUTXO.
// Use with [zapv2.Read] / [zapv2.Write] for type-safe access.
// Byte-array fields are emitted as standalone functions, see below.
var ZKVMUTXOSchemaFields = struct {
	OutputIndex zapv2.Field[ZKVMUTXOSchema, uint32]
	Height zapv2.Field[ZKVMUTXOSchema, uint64]
	CommitmentOff zapv2.Field[ZKVMUTXOSchema, uint32]
	CommitmentLen zapv2.Field[ZKVMUTXOSchema, uint32]
	CiphertextOff zapv2.Field[ZKVMUTXOSchema, uint32]
	CiphertextLen zapv2.Field[ZKVMUTXOSchema, uint32]
	EphemeralPKOff zapv2.Field[ZKVMUTXOSchema, uint32]
	EphemeralPKLen zapv2.Field[ZKVMUTXOSchema, uint32]
}{
	OutputIndex: zapv2.At[ZKVMUTXOSchema, uint32](4),
	Height: zapv2.At[ZKVMUTXOSchema, uint64](8),
	CommitmentOff: zapv2.At[ZKVMUTXOSchema, uint32](48),
	CommitmentLen: zapv2.At[ZKVMUTXOSchema, uint32](52),
	CiphertextOff: zapv2.At[ZKVMUTXOSchema, uint32](56),
	CiphertextLen: zapv2.At[ZKVMUTXOSchema, uint32](60),
	EphemeralPKOff: zapv2.At[ZKVMUTXOSchema, uint32](64),
	EphemeralPKLen: zapv2.At[ZKVMUTXOSchema, uint32](68),
}

// NewZKVMUTXO builds a fresh ZKVMUTXO in a ZAP buffer.
//
// Hand-rolled fast path: inlines v1 primitives ([zap.NewBuilder],
// [*Builder.StartObject], [*ObjectBuilder.Set*], [*Builder.Finish])
// so the entire build expands at the call site. Result: 1 heap
// alloc (the buffer), zero overhead vs v1.
func NewZKVMUTXO(outputIndex uint32, height uint64, commitmentOff uint32, commitmentLen uint32, ciphertextOff uint32, ciphertextLen uint32, ephemeralPKOff uint32, ephemeralPKLen uint32, txID [32]byte) (zapv2.View[ZKVMUTXOSchema], []byte) {
	b := zap.NewBuilder(zap.HeaderSize + SizeZKVMUTXO)
	ob := b.StartObject(SizeZKVMUTXO)
	ob.SetUint8(0, uint8(KindZKVMUTXO))
	ob.SetUint32(OffsetZKVMUTXO_OutputIndex, outputIndex)
	ob.SetUint64(OffsetZKVMUTXO_Height, height)
	ob.SetUint32(OffsetZKVMUTXO_CommitmentOff, commitmentOff)
	ob.SetUint32(OffsetZKVMUTXO_CommitmentLen, commitmentLen)
	ob.SetUint32(OffsetZKVMUTXO_CiphertextOff, ciphertextOff)
	ob.SetUint32(OffsetZKVMUTXO_CiphertextLen, ciphertextLen)
	ob.SetUint32(OffsetZKVMUTXO_EphemeralPKOff, ephemeralPKOff)
	ob.SetUint32(OffsetZKVMUTXO_EphemeralPKLen, ephemeralPKLen)
	ob.SetBytesFixed(OffsetZKVMUTXO_TxID, txID[:])
	rootOff := ob.FinishAsRoot()
	buf := b.Finish()
	end := rootOff + SizeZKVMUTXO
	return zapv2.AsView[ZKVMUTXOSchema](zapv2.RawFromSlices(buf, rootOff, end)), buf
}

// WrapZKVMUTXO parses a ZAP buffer into a typed
// [zapv2.View[ZKVMUTXO]]. Validates the wire frame and the kind
// discriminator at offset 0; returns [*zapv2.SchemaError] on kind
// mismatch.
//
// Hand-rolled fast path: inlines [zap.Parse] (which is itself
// inlineable). Zero heap allocs on the happy path; matches v1
// hand-rolled performance.
func WrapZKVMUTXO(b []byte) (zapv2.View[ZKVMUTXOSchema], error) {
	msg, err := zap.Parse(b)
	if err != nil {
		return zapv2.View[ZKVMUTXOSchema]{}, err
	}
	root := msg.Root()
	if got := root.Uint8(0); got != uint8(KindZKVMUTXO) {
		return zapv2.View[ZKVMUTXOSchema]{}, zapv2.NewSchemaError(
			KindZKVMUTXO, zapv2.KindByte(got), "ZKVMUTXO")
	}
	data := msg.Bytes()
	rootOff := root.Offset()
	end := rootOff + SizeZKVMUTXO
	if end > len(data) {
		end = len(data) // Read returns zero on OOB; v1 graceful degradation
	}
	return zapv2.AsView[ZKVMUTXOSchema](zapv2.RawFromSlices(data, rootOff, end)), nil
}

// ZKVMUTXOTxID reads the 32-byte inline TxID field of ZKVMUTXO.
//
// Zero-copy on the read side (v1's Object.BytesFixedSlice returns
// a sub-slice of the underlying buffer); the returned [32]byte is a
// value copy so the caller's slot owns the bytes after the View's
// buffer is freed.
func ZKVMUTXOTxID(v zapv2.View[ZKVMUTXOSchema]) [32]byte {
	msg := zap.WrapBuffer(v.Bytes())
	obj := msg.RootObjectAt(int(zapv2.RootOff(v)))
	slice := obj.BytesFixedSlice(OffsetZKVMUTXO_TxID, 32)
	var out [32]byte
	if len(slice) == 32 {
		copy(out[:], slice)
	}
	return out
}

